default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

production:
  <<: *default
  database: postgres://yjgcdsbmjdpawg:7aea77342e3acb589e388016cb7af714d5a32eeaf0e41bac5cfd7514ecac6cba@ec2-3-232-218-211.compute-1.amazonaws.com:5432/ddioqna4f3m9cl
